[font]
size = 10.5

[font.normal]
family = 'Hurmit Nerd Font'
style = 'Light'

[font.bold]
family = 'Hurmit Nerd Font'
style = 'Light'

[font.italic]
family = 'Hurmit Nerd Font'
style = 'Light'

[font.bold_italic]
family = 'Hurmit Nerd Font'
style = 'Light'

[font.offset]
x = 1
y = 0

[font.glyph_offset]
x = 0
y = -1
