[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Light"

[font.offset]
x = 1
y = 2

[font.glyph_offset]
x = 0
y = 1

