[font]
size = 11.5

[font.normal]
family = 'Mononoki Nerd Font'
style = 'Regular'

[font.bold]
family = 'Mononoki Nerd Font'
style = 'Regular'

[font.italic]
family = 'Mononoki Nerd Font'
style = 'Regular'

[font.bold_italic]
family = 'Mononoki Nerd Font'
style = 'Regular'

[font.offset]
x = 1
y = 3

[font.glyph_offset]
x = 0
y = 1
