[font]
size = 10

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[font.bold]
family = "0xProto Nerd Font"
style = "Regular"

[font.italic]
family = "0xProto Nerd Font"
style = "Regular"

[font.bold_italic]
family = "0xProto Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 2

[font.glyph_offset]
x = 0
y = 1

