# https://github.com/projekt0n/github-theme-contrib/blob/main/themes/alacritty/github_light.yml#L4

[colors.primary]
background = '#eeeeee'
foreground = '#1F2328'

[colors.cursor]
text = '#ffffff'
cursor = '#1f2328'

[colors.normal]
black = '#24292f'
red = '#cf222e'
green = '#116329'
yellow = '#4d2d00'
blue = '#0969da'
magenta = '#8250df'
cyan = '#1b7c83'
white = '#6e7781'

[colors.bright]
black = '#57606a'
red = '#a40e26'
green = '#1a7f37'
yellow = '#633c01'
blue = '#218bff'
magenta = '#8250df'
cyan = '#1b7c83'
white = '#6e7781'
